# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetalCli < Formula
  desc "Official Equinix Metal CLI"
  homepage "https://metal.equinix.com/developers/docs/libraries/cli/"
  version "0.7.2-alpha1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/equinix/metal-cli/releases/download/v0.7.2-alpha1/metal-darwin-amd64"
      sha256 "b978562b898601466d39d00665505df4bfaf90b30c24fe97c3d514efab9d79e8"

      def install
        bin.install "metal-darwin-amd64" => "metal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/equinix/metal-cli/releases/download/v0.7.2-alpha1/metal-linux-amd64"
      sha256 "1cdfb53ccb172ac105183023ccd450ddec4407a9ed0a5bab55fe09e75058fb9f"

      def install
        bin.install "metal-linux-amd64" => "metal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/equinix/metal-cli/releases/download/v0.7.2-alpha1/metal-linux-arm64"
      sha256 "a7d2b7e3e9e921e322f2a071f1f49bb5869e13392af1d7961b77c90368e92b83"

      def install
        bin.install "metal-linux-arm64" => "metal"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/equinix/metal-cli/releases/download/v0.7.2-alpha1/metal-linux-armv6"
      sha256 "974f702e6cf3a862e5d285b2cc42b195a843c87249929995a78c22d67391633a"

      def install
        bin.install "metal-linux-armv6" => "metal"
      end
    end
  end

  depends_on "go" => :build
end
