# This file was generated by GoReleaser. DO NOT EDIT.
cask "equinix" do
  name "equinix"
  desc "Official Equinix CLI"
  homepage "https://docs.equinix.com/"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "equinix"

  on_macos do
    on_intel do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-darwin-amd64.zip"
      sha256 "c51e4c7063b5de84259bd8cb4854a7dee53d5a3658ce52d0222045e86b003dae"
    end
    on_arm do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-darwin-arm64.zip"
      sha256 "f77abd7ad860a9b70af74422301d1e9472e04e38394e860b8f77667c958850d0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-linux-amd64.zip"
      sha256 "49f27c32d6f8d5379ceb26757a981d99541dab2dde1ed186caaf42574fe92d13"
    end
    on_arm do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-linux-arm64.zip"
      sha256 "7e0c2ef088a1722d7dad02bcc6c015bf9878b5939f612da5d596b150aafcc668"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/equinix"]
    end
  end

  # No zap stanza required
end
