# This file was generated by GoReleaser. DO NOT EDIT.
cask "equinix" do
  name "equinix"
  desc "Official Equinix CLI"
  homepage "https://docs.equinix.com/"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "equinix"

  on_macos do
    on_intel do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-darwin-amd64.zip"
      sha256 "7a1a603a2a660e2357322f153fc7c6e2e18dd058309a9a1e77dfd5719a204d0c"
    end
    on_arm do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-darwin-arm64.zip"
      sha256 "41c6a48a6f6360acf2b5110ee4c811796fe781dcf418c14354c5fdb9703dda48"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-linux-amd64.zip"
      sha256 "e7a134b2245f447bfbefab29dd2994e0e10ab2800b352bdd111ba070e473690a"
    end
    on_arm do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-linux-arm64.zip"
      sha256 "ccc66f103ff58f9856470198c4e78d350d22d7da45fb18d138243b536dbfb62a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/equinix"]
    end
  end

  # No zap stanza required
end
