# This file was generated by GoReleaser. DO NOT EDIT.
cask "equinix" do
  name "equinix"
  desc "Official Equinix CLI"
  homepage "https://docs.equinix.com/"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "equinix"

  on_macos do
    on_intel do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-darwin-amd64.zip"
      sha256 "1f3b44350b1117c6e4cb64024756fae067a62604d96a13c3c047d1bbe7f581c6"
    end
    on_arm do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-darwin-arm64.zip"
      sha256 "820d0ff547b6109d94735f12f22040faf2861a7916ced0055c7cd4a56170cfc6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-linux-amd64.zip"
      sha256 "65a9120cad6fda3aeed987596e60840a5c485fe987b17eb4fdab810af28274a6"
    end
    on_arm do
      url "https://github.com/equinix/cli/releases/download/v#{version}/equinix-linux-arm64.zip"
      sha256 "68ce517787dfedb34ced62e3b47dc2cfc296655b0800278347900e4008c6799a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/equinix"]
    end
  end

  # No zap stanza required
end
