# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetalCLI < Formula
  desc "Equinix Metal CLI"
  homepage "https://githubcom/equinix/metal-cli"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/equinix/metal-cli/releases/download/v0.6.0/metal-darwin-amd64"
      sha256 "ebcb8bd18e83bd39a6a6cf711802654b349f83c7f75de27e1113b704d9682315"
      def install
        bin.install "metal-darwin-amd64" => "metal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/equinix/metal-cli/releases/download/v0.6.0/metal-linux-armv6"
      sha256 "67f8aff5a2fdc156a192125f0b2d9cd73208da5a764b71b247f41c996d13e8b2"
      def install
        bin.install "metal-linux-armv6" => "metal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/equinix/metal-cli/releases/download/v0.6.0/metal-linux-amd64"
      sha256 "50f575b8e5355cd603df3bcae4ceac30fe4fdec63da61d2fb06f02163fb267d2"
      def install
        bin.install "metal-linux-amd64" => "metal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/equinix/metal-cli/releases/download/v0.6.0/metal-linux-arm64"
      sha256 "36797022316a2fc62db884170d2946eef9022848aa5540419b08d8d0d25e1569"
      def install
        bin.install "metal-linux-arm64" => "metal"
      end
    end
  end

  test do
    system "#{bin}/metal -v"
  end
end
